import React, { useState } from "react";
import { 
  Plus, Folder, Clock, Search, BookOpen, 
  Image as ImageIcon, Box, Sparkles, ChevronRight, 
  Play, Compass, RefreshCw, Trash2, ArrowUpRight,
  Send, Code2, Users, HelpCircle, Laptop, Settings, CheckCircle2, Terminal, Network, X
} from "lucide-react";
import { Project } from "../types";

interface DashboardViewProps {
  projects: Project[];
  activeProjectId: string;
  onOpenProject: (id: string) => void;
  onDeleteProject: (id: string) => void;
  onCreateNewProject: (name: string, description: string, type: "Websites" | "Games" | "Images" | "Models", initialFiles: Record<string, string>) => void;
  onSelectLesson: (id: string) => void;
  userName: string;
  userUsername?: string;
  onNewSpaceRequest?: () => void;
  onNavigateView?: (view: any) => void;
  dailyQueries: number;
  completedLessonSteps: Record<string, boolean[]>;
  storageBytes: number;
  isGuest?: boolean;
}

export default function DashboardView({
  projects,
  activeProjectId,
  onOpenProject,
  onDeleteProject,
  onCreateNewProject,
  onSelectLesson,
  userName,
  userUsername,
  onNewSpaceRequest,
  onNavigateView,
  dailyQueries,
  completedLessonSteps,
  storageBytes,
  isGuest = false
}: DashboardViewProps) {
  const [searchQuery, setSearchQuery] = useState("");
  const [newProjName, setNewProjName] = useState("");
  const [newProjType, setNewProjType] = useState<"Websites" | "Games" | "Images" | "Models">("Websites");
  const [newProjDesc, setNewProjDesc] = useState("");
  const [showCreateModal, setShowCreateModal] = useState(false);

  // Dynamic Exact calculations
  const totalChats = projects.reduce((acc, p) => acc + (p.chatHistory?.length || 0), 0) + dailyQueries;
  
  const totalMediaAssets = projects.reduce((acc, p) => {
    return acc + (p.generatedImages?.length || 0) + (p.generated3D?.length || 0);
  }, 0);

  const completedLessonsCount = Object.keys(completedLessonSteps).filter(key => 
    completedLessonSteps[key]?.some(step => step)
  ).length;

  const storageMB = (storageBytes / (1024 * 1024)).toFixed(2);

  // Filter projects by search
  const filteredProjects = projects.filter(p => 
    p.name.toLowerCase().includes(searchQuery.toLowerCase()) || 
    p.description.toLowerCase().includes(searchQuery.toLowerCase())
  );

  // Template blueprints
  const templates = [
    {
      name: "Responsive Landing Page",
      desc: "An elegant, visual-focused promotional page with interactive dark accents and custom animations.",
      type: "Websites" as const,
      files: {
        "index.html": `<!DOCTYPE html>
<html>
<head>
  <script src="https://cdn.tailwindcss.com"></script>
  <style>
    @keyframes float { 0%, 100% { transform: translateY(0); } 50% { transform: translateY(-10px); } }
    .animate-float { animation: float 4s ease-in-out infinite; }
  </style>
</head>
<body class="bg-slate-950 text-slate-100 min-h-screen flex flex-col justify-between selection:bg-teal-500/30 selection:text-teal-300 font-sans">
  <header class="p-6 flex justify-between items-center border-b border-slate-900 bg-slate-950/80 backdrop-blur">
    <div class="flex items-center space-x-2">
      <div class="h-6 w-6 rounded bg-teal-500 flex items-center justify-center font-bold text-slate-950 text-xs">F</div>
      <span class="font-extrabold text-sm tracking-tight text-white">FutureWeb</span>
    </div>
    <nav class="space-x-4 text-xs font-semibold text-slate-400">
      <a href="#" class="hover:text-white transition">Product</a>
      <a href="#" class="hover:text-white transition">Pricing</a>
      <a href="#" class="hover:text-white transition">Contact</a>
    </nav>
  </header>

  <main class="max-w-4xl mx-auto p-12 text-center space-y-6">
    <h1 class="text-5xl font-extrabold tracking-tight text-white">Forge Infinite Layouts</h1>
    <p class="text-slate-400 text-sm max-w-lg mx-auto">This responsive interface template was auto-generated by the ForgeAI engine inside an isolated runtime simulator.</p>
    <div class="pt-6 animate-float">
      <span class="inline-block px-5 py-2.5 bg-gradient-to-r from-teal-500 to-cyan-500 hover:opacity-90 cursor-pointer text-slate-950 text-xs font-bold rounded-lg shadow-lg shadow-teal-500/20">Explore FutureWeb Systems</span>
    </div>
  </main>

  <footer class="p-6 text-center border-t border-slate-900 text-[10px] text-slate-600">
    © 2026 FutureWeb Inc. Created inside ForgeAI Cloud Studio.
  </footer>
</body>
</html>`
      }
    },
    {
      name: "Retro Space Physics Game",
      desc: "A fully playable retro space shooting game built using canvas loops, touch controls, and audio effects.",
      type: "Games" as const,
      files: {
        "index.html": `<!DOCTYPE html>
<html>
<head>
  <script src="https://cdn.tailwindcss.com"></script>
</head>
<body class="bg-slate-950 text-slate-100 flex flex-col items-center justify-center min-h-screen font-mono p-4">
  <div class="text-center space-y-3">
    <h1 class="text-xl font-bold text-teal-400">🛸 Retro Space Physics Defender</h1>
    <p class="text-[10px] text-slate-500">Left/Right Arrow or Touch buttons to guide your cannon. Space to fire.</p>
    
    <div class="relative">
      <canvas id="gameCanvas" width="400" height="300" class="border border-slate-800 bg-slate-900 rounded-lg shadow-lg"></canvas>
    </div>

    <div class="flex space-x-2 justify-center">
      <button id="leftBtn" class="px-4 py-2 bg-slate-800 rounded font-bold text-xs select-none">◀ Left</button>
      <button id="fireBtn" class="px-6 py-2 bg-teal-500 text-slate-950 font-bold text-xs rounded select-none">🔥 Fire</button>
      <button id="rightBtn" class="px-4 py-2 bg-slate-800 rounded font-bold text-xs select-none">Right ▶</button>
    </div>
  </div>

  <script>
    const canvas = document.getElementById("gameCanvas");
    const ctx = canvas.getContext("2d");

    let playerX = 180;
    let bullets = [];
    let aliens = [];
    let score = 0;

    for (let i = 0; i < 5; i++) {
      aliens.push({ x: 50 + i * 70, y: 40, active: true });
    }

    function gameLoop() {
      ctx.clearRect(0, 0, 400, 300);

      ctx.fillStyle = "#2dd4bf";
      ctx.fillRect(playerX, 270, 40, 15);

      ctx.fillStyle = "#ff007f";
      bullets.forEach((b, idx) => {
        b.y -= 5;
        ctx.fillRect(b.x, b.y, 4, 8);
        if (b.y < 0) bullets.splice(idx, 1);

        aliens.forEach(a => {
          if (a.active && b.x > a.x && b.x < a.x + 30 && b.y > a.y && b.y < a.y + 20) {
            a.active = false;
            bullets.splice(idx, 1);
            score += 10;
          }
        });
      });

      ctx.fillStyle = "#a78bfa";
      let activeAliens = 0;
      aliens.forEach(a => {
        if (a.active) {
          activeAliens++;
          ctx.fillRect(a.x, a.y, 30, 20);
        }
      });

      ctx.fillStyle = "#ffffff";
      ctx.font = "10px monospace";
      ctx.fillText("SCORE: " + score, 10, 20);

      if (activeAliens === 0) {
        ctx.fillText("VICTORY! All Aliens Defeated.", 120, 150);
      }

      requestAnimationFrame(gameLoop);
    }

    document.getElementById("leftBtn").addEventListener("click", () => { playerX = Math.max(0, playerX - 15); });
    document.getElementById("rightBtn").addEventListener("click", () => { playerX = Math.min(360, playerX + 15); });
    document.getElementById("fireBtn").addEventListener("click", () => { bullets.push({ x: playerX + 18, y: 260 }); });

    document.addEventListener("keydown", (e) => {
      if (e.key === "ArrowLeft") playerX = Math.max(0, playerX - 15);
      if (e.key === "ArrowRight") playerX = Math.min(360, playerX + 15);
      if (e.key === " ") bullets.push({ x: playerX + 18, y: 260 });
    });

    gameLoop();
  </script>
</body>
</html>`
      }
    }
  ];

  const handleCreateProject = (e: React.FormEvent) => {
    e.preventDefault();
    if (!newProjName.trim()) return;

    onCreateNewProject(
      newProjName.trim(),
      newProjDesc.trim() || "Custom Workspace built instantly via ForgeAI.",
      newProjType,
      {
        "index.html": `<!DOCTYPE html>
<html>
<body class="bg-slate-900 text-white p-12 text-center">
  <h1 class="text-3xl font-extrabold mb-4">${newProjName} Active Space</h1>
  <p class="text-sm text-slate-400">Deploy custom API routes or request Forge Workspace paired assistance.</p>
</body>
</html>`
      }
    );

    setNewProjName("");
    setNewProjDesc("");
    setShowCreateModal(false);
  };

  const recommendedLessons = [
    {
      id: "loops",
      title: "Interactive Game Loop Architecture",
      desc: "Learn physics rendering, rigid collisions, and frame throttling mechanics inside standard browser canvases.",
      duration: "10 mins",
      difficulty: "Intermediate"
    },
    {
      id: "state",
      title: "Asynchronous APIs & State Machines",
      desc: "Trace promises, state hooks, and proxy routing line-by-line using our compiler debug sandbox.",
      duration: "15 mins",
      difficulty: "Advanced"
    }
  ];

  // Floating ambient icons configuration
  const floatingIcons = [
    { label: "⚡", style: { top: "12%", left: "5%", animationDelay: "0s", animationDuration: "14s" } },
    { label: "🛰️", style: { top: "45%", right: "8%", animationDelay: "2s", animationDuration: "18s" } },
    { label: "🔮", style: { bottom: "15%", left: "12%", animationDelay: "4s", animationDuration: "16s" } },
    { label: "🚀", style: { top: "25%", right: "25%", animationDelay: "1s", animationDuration: "20s" } },
    { label: "💻", style: { bottom: "25%", right: "15%", animationDelay: "3s", animationDuration: "15s" } },
  ];

  // Quick Action List items requested by the user
  const quickActions = [
    { icon: "💬", label: "AI Chat", view: "chat", sub: "Prompt Studio" },
    { icon: "🌐", label: "Website", type: "Websites" as const, sub: "Vite SPA App" },
    { icon: "📱", label: "Android", type: "Websites" as const, sub: "Kotlin Setup" },
    { icon: "🎮", label: "Roblox", type: "Games" as const, sub: "Lua Sandbox" },
    { icon: "🧱", label: "Minecraft Plugin", type: "Games" as const, sub: "Java Spigot" },
    { icon: "🐍", label: "Python App", type: "Websites" as const, sub: "FastAPI Script" },
    { icon: "🤖", label: "Discord Bot", type: "Games" as const, sub: "Event Hooks" },
    { icon: "🎨", label: "Image", view: "assets", sub: "Pro Synthesis" },
    { icon: "📦", label: "API", type: "Websites" as const, sub: "REST Routes" },
    { icon: "🖥", label: "Desktop App", type: "Websites" as const, sub: "Electron Container" }
  ];

  // Execute Quick Start triggers
  const handleQuickAction = (act: typeof quickActions[0]) => {
    if (act.view && onNavigateView) {
      onNavigateView(act.view);
    } else if (act.type) {
      setNewProjType(act.type);
      setNewProjName(`New ${act.label} Project`);
      setNewProjDesc(`An interactive workspace initialized for ${act.label} development.`);
      setShowCreateModal(true);
    }
  };

  return (
    <div className="flex-1 overflow-y-auto bg-slate-950 p-6 sm:p-10 space-y-10 selection:bg-teal-500/30 selection:text-teal-300 relative">
      
      {/* Floating particles background styling */}
      <style>{`
        @keyframes customFloat {
          0%, 100% { transform: translateY(0) rotate(0deg); opacity: 0.2; }
          50% { transform: translateY(-20px) rotate(10deg); opacity: 0.45; }
        }
        .animate-bg-float {
          animation: customFloat 15s ease-in-out infinite;
        }
      `}</style>

      {/* Background Floating Elements */}
      <div className="absolute inset-0 pointer-events-none overflow-hidden select-none z-0">
        {floatingIcons.map((ico, index) => (
          <div 
            key={index} 
            style={ico.style} 
            className="absolute text-2xl filter blur-[1px] animate-bg-float opacity-30 transition-all duration-1000"
          >
            {ico.label}
          </div>
        ))}
      </div>

      {/* 1. Welcome Header Banner with Live Broadcast Marquee */}
      <div className="relative overflow-hidden p-8 sm:p-10 rounded-3xl bg-gradient-to-br from-slate-900/60 via-slate-950/90 to-slate-950 border border-slate-900/80 shadow-2xl flex flex-col md:flex-row items-center justify-between gap-6 z-10">
        <div className="absolute inset-0 bg-grid-white/[0.02] bg-[size:16px_16px] pointer-events-none"></div>
        <div className="space-y-3.5 z-10 text-left max-w-xl">
          <div className="flex items-center space-x-2">
            <span className="relative flex h-2.5 w-2.5">
              <span className="animate-ping absolute inline-flex h-full w-full rounded-full bg-teal-400 opacity-75"></span>
              <span className="relative inline-flex rounded-full h-2.5 w-2.5 bg-teal-500"></span>
            </span>
            <span className="text-[10px] font-mono text-teal-400 font-extrabold uppercase tracking-widest bg-teal-500/10 px-2 py-0.5 rounded border border-teal-500/20">System Live</span>
          </div>
          <h1 className="text-3xl sm:text-4xl font-extrabold text-white tracking-tight leading-none">
            Good Evening 👋
          </h1>
          <p className="text-sm text-slate-400 leading-relaxed">
            Welcome back, <span className="text-teal-400 font-black">@{userUsername || userName.toLowerCase().replace(/[^a-z0-9]/g, "_")}</span>. Continue your AI workspace or start something new with ForgeAI's instant deployment compiler.
          </p>
        </div>
        <div className="relative shrink-0 z-10 flex gap-2">
          <button 
            id="create-new-space-hero-btn"
            onClick={() => onNewSpaceRequest ? onNewSpaceRequest() : setShowCreateModal(true)}
            className="px-5 py-3 bg-gradient-to-r from-teal-500 to-cyan-400 hover:opacity-90 active:scale-98 text-slate-950 text-xs font-black uppercase tracking-wider rounded-xl transition shadow-lg shadow-teal-500/10 flex items-center space-x-2 cursor-pointer"
          >
            <Plus className="h-4 w-4 stroke-[3px]" />
            <span>New Space</span>
          </button>
        </div>
      </div>

      {/* 2. Announcements / Live Broadcast Marquee bar */}
      <div className="p-3 bg-gradient-to-r from-purple-950/35 via-slate-900/60 to-purple-950/35 border border-purple-950 rounded-2xl flex items-center justify-between gap-4 z-10 overflow-hidden text-xs">
        <span className="px-2.5 py-0.5 bg-purple-500/15 border border-purple-500/20 text-purple-400 font-bold uppercase tracking-wider text-[9px] font-mono shrink-0 rounded">Live Broadcast</span>
        <div className="flex-1 overflow-hidden relative">
          <div className="whitespace-nowrap font-medium text-slate-300 font-mono text-[11px] animate-[marquee_25s_linear_infinite]">
            🚀 ForgeAI v3.5 is now fully active! Armed with dual-stream multimodal synthesizers, low-latency Audio Modality, and ultra-high-resolution image generation. Deploy instant sandbox runtimes on port 3000.
          </div>
        </div>
        <style>{`
          @keyframes marquee {
            0% { transform: translate3d(100%, 0, 0); }
            100% { transform: translate3d(-100%, 0, 0); }
          }
        `}</style>
      </div>

      {/* 3. Start Building / Quick Start Action Row */}
      <div className="space-y-4 z-10 relative">
        <div className="flex items-center justify-between">
          <h2 className="text-sm font-bold text-slate-200 flex items-center space-x-2">
            <span className="text-yellow-400 font-bold text-base">⚡</span>
            <span>Quick Start Actions</span>
          </h2>
          <span className="text-[10px] font-mono text-slate-500">One-click compile deployment</span>
        </div>

        <div className="grid grid-cols-2 sm:grid-cols-3 md:grid-cols-5 gap-4">
          {quickActions.map((act, idx) => (
            <button 
              id={`quick-start-action-${idx}`}
              key={idx}
              onClick={() => handleQuickAction(act)}
              className="p-3 bg-slate-900/40 hover:bg-slate-900 border border-slate-900 hover:border-teal-500/30 rounded-2xl text-left transition duration-300 group hover:-translate-y-1 hover:shadow-xl hover:shadow-teal-500/5 cursor-pointer flex flex-col justify-between h-24 relative"
            >
              <div className="flex justify-between items-start">
                <span className="text-xl select-none group-hover:scale-110 transition duration-300">{act.icon}</span>
                <ArrowUpRight className="h-3 w-3 text-slate-600 group-hover:text-teal-400 transition" />
              </div>
              <div>
                <span className="block text-xs font-bold text-white group-hover:text-teal-400 transition truncate leading-none mb-1">{act.label}</span>
                <span className="block text-[9px] text-slate-500 font-mono truncate">{act.sub}</span>
              </div>
            </button>
          ))}
        </div>
      </div>

      {/* 4. Alive statistics widgets (Bento Grid) with visual accent color layout */}
      <div className="space-y-4 z-10 relative">
        <h2 className="text-sm font-bold text-slate-200 flex items-center space-x-2">
          <Sparkles className="h-4 w-4 text-teal-400" />
          <span>Interactive Engine Statistics</span>
        </h2>

        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-5 gap-4">
          
          {/* Blue Accent: Project Sandbox Matrix */}
          <div id="stats-blue-projects-card" className="p-4 bg-gradient-to-b from-slate-900/40 to-slate-950 hover:to-slate-900 border border-slate-900 hover:border-blue-500/20 rounded-2xl transition duration-300 hover:shadow-lg hover:shadow-blue-500/5 flex flex-col justify-between space-y-4 group">
            <div className="space-y-1.5">
              <div className="flex justify-between items-center">
                <span className="text-[9px] font-bold text-blue-400 font-mono tracking-wider uppercase">Sandbox Registry</span>
                <Folder className="h-3.5 w-3.5 text-blue-400" />
              </div>
              <h3 className="text-2xl font-black text-white">{projects.length} Spaces</h3>
              <p className="text-[10px] text-slate-500 leading-normal">Compiled workspace instances configured stably.</p>
            </div>
            <div className="pt-2 border-t border-slate-900 text-[9px] font-mono text-slate-400 flex items-center justify-between">
              <span>Status: Synchronized</span>
              <span className="h-1.5 w-1.5 rounded-full bg-blue-400"></span>
            </div>
          </div>

          {/* Cyan Accent: AI Chat Synthesis Hub */}
          <div id="stats-cyan-ai-card" className="p-4 bg-gradient-to-b from-slate-900/40 to-slate-950 hover:to-slate-900 border border-slate-900 hover:border-cyan-500/20 rounded-2xl transition duration-300 hover:shadow-lg hover:shadow-cyan-500/5 flex flex-col justify-between space-y-4 group">
            <div className="space-y-1.5">
              <div className="flex justify-between items-center">
                <span className="text-[9px] font-bold text-cyan-400 font-mono tracking-wider uppercase">AI Prompt Matrix</span>
                <Sparkles className="h-3.5 w-3.5 text-cyan-400" />
              </div>
              <h3 className="text-2xl font-black text-white">{totalChats} Runs</h3>
              <p className="text-[10px] text-slate-500 leading-normal">Total interactive AI dialogues executed in sandbox.</p>
            </div>
            <div className="pt-2 border-t border-slate-900 text-[9px] font-mono text-slate-400 flex items-center justify-between">
              <span>Latency: 18ms</span>
              <span className="h-1.5 w-1.5 rounded-full bg-cyan-400"></span>
            </div>
          </div>

          {/* Orange Accent: Multimodal Assets Forge */}
          <div id="stats-orange-assets-card" className="p-4 bg-gradient-to-b from-slate-900/40 to-slate-950 hover:to-slate-900 border border-slate-900 hover:border-orange-500/20 rounded-2xl transition duration-300 hover:shadow-lg hover:shadow-orange-500/5 flex flex-col justify-between space-y-4 group">
            <div className="space-y-1.5">
              <div className="flex justify-between items-center">
                <span className="text-[9px] font-bold text-orange-400 font-mono tracking-wider uppercase">Media Assets</span>
                <Box className="h-3.5 w-3.5 text-orange-400" />
              </div>
              <h3 className="text-2xl font-black text-white">{totalMediaAssets} Assets</h3>
              <p className="text-[10px] text-slate-500 leading-normal">Synthetic images, videos, and 3D wireframe outputs.</p>
            </div>
            <div className="pt-2 border-t border-slate-900 text-[9px] font-mono text-slate-400 flex items-center justify-between">
              <span>Ready for import</span>
              <span className="h-1.5 w-1.5 rounded-full bg-orange-400"></span>
            </div>
          </div>

          {/* Purple Accent: Software Academy Progress */}
          <div id="stats-purple-lessons-card" className="p-4 bg-gradient-to-b from-slate-900/40 to-slate-950 hover:to-slate-900 border border-slate-900 hover:border-purple-500/20 rounded-2xl transition duration-300 hover:shadow-lg hover:shadow-purple-500/5 flex flex-col justify-between space-y-4 group">
            <div className="space-y-1.5">
              <div className="flex justify-between items-center">
                <span className="text-[9px] font-bold text-purple-400 font-mono tracking-wider uppercase">Academy Path</span>
                <BookOpen className="h-3.5 w-3.5 text-purple-400" />
              </div>
              <h3 className="text-2xl font-black text-white">{completedLessonsCount} / 15 Finished</h3>
              <p className="text-[10px] text-slate-500 leading-normal">Interactive tutorials and architectural lessons finished.</p>
            </div>
            <div className="pt-2 border-t border-slate-900 text-[9px] font-mono text-slate-400 flex items-center justify-between">
              <span>Level: Intermediate</span>
              <span className="h-1.5 w-1.5 rounded-full bg-purple-400"></span>
            </div>
          </div>

          {/* Green Accent: Cloud Storage Stats */}
          <div id="stats-green-cloud-card" className="p-4 bg-gradient-to-b from-slate-900/40 to-slate-950 hover:to-slate-900 border border-slate-900 hover:border-emerald-500/20 rounded-2xl transition duration-300 hover:shadow-lg hover:shadow-emerald-500/5 flex flex-col justify-between space-y-4 group">
            <div className="space-y-1.5">
              <div className="flex justify-between items-center">
                <span className="text-[9px] font-bold text-emerald-400 font-mono tracking-wider uppercase">Node Storage</span>
                <Network className="h-3.5 w-3.5 text-emerald-400" />
              </div>
              <h3 className="text-xl font-black text-white">
                {storageBytes < 1024 * 1024 * 1024 ? `${(storageBytes / (1024 * 1024)).toFixed(2)} MB` : `${(storageBytes / (1024 * 1024 * 1024)).toFixed(2)} GB`} Used
              </h3>
              <p className="text-[10px] text-slate-500 leading-normal">
                {isGuest ? "Free Tier allocation (1.0 GB limit)" : "Premium cloud allocation (5000.0 GB (5 TB) limit)"}
              </p>
            </div>
            <div className="pt-2 border-t border-slate-900 text-[9px] font-mono text-slate-400 flex items-center justify-between">
              <span>Quota: {isGuest ? "1.00 GB max" : "5000.00 GB (5 TB) max"}</span>
              <span className="h-1.5 w-1.5 rounded-full bg-emerald-400 animate-pulse"></span>
            </div>
          </div>

        </div>
      </div>

      {/* 5. What was I working on? (Continue working) & Daily limits block */}
      <div className="grid grid-cols-1 lg:grid-cols-12 gap-8 z-10 relative">
        
        {/* Left Side: Recent workspace modules */}
        <div className="lg:col-span-8 space-y-4">
          <div className="flex items-center justify-between">
            <h2 className="text-sm font-bold text-slate-200 flex items-center space-x-2">
              <Folder className="h-4 w-4 text-teal-400" />
              <span>Continue Working (Recent Projects)</span>
            </h2>
            <span className="text-[10px] font-mono text-slate-500">{filteredProjects.length} spaces matching</span>
          </div>

          {filteredProjects.length === 0 ? (
            <div className="p-10 bg-slate-900/20 border border-slate-900 rounded-3xl text-center text-slate-500 text-xs">
              No matching spaces found. Create a custom space or deploy a template below to start compiling!
            </div>
          ) : (
            <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
              {filteredProjects.map((p) => {
                const isActive = p.id === activeProjectId;
                return (
                  <div 
                    id={`project-card-${p.id}`}
                    key={p.id}
                    className={`p-5 bg-slate-900/40 hover:bg-slate-900 border rounded-2xl flex flex-col justify-between space-y-4 transition duration-300 group ${
                      isActive ? 'border-teal-500/40 bg-teal-950/5' : 'border-slate-900 hover:border-slate-800'
                    }`}>
                    <div className="space-y-2">
                      <div className="flex items-center justify-between">
                        <span className={`text-[9px] font-mono uppercase px-2 py-0.5 rounded font-bold ${
                          p.type === 'Games' ? 'bg-purple-500/10 text-purple-400' :
                          p.type === 'Models' ? 'bg-indigo-500/10 text-indigo-400' :
                          'bg-teal-500/10 text-teal-400'
                        }`}>
                          {p.type}
                        </span>
                        <div className="opacity-0 group-hover:opacity-100 transition">
                          <button 
                            onClick={(e) => { e.stopPropagation(); onDeleteProject(p.id); }}
                            className="p-1 text-slate-500 hover:text-red-400 transition shrink-0"
                            title="Delete Space"
                          >
                            <Trash2 className="h-3.5 w-3.5" />
                          </button>
                        </div>
                      </div>
                      <h3 className="text-sm font-bold text-white group-hover:text-teal-400 transition truncate leading-snug">{p.name}</h3>
                      <p className="text-[11px] text-slate-500 line-clamp-2 leading-relaxed">{p.description}</p>
                    </div>

                    <div className="flex items-center justify-between pt-3 border-t border-slate-900/60 text-[10px] font-mono text-slate-500">
                      <span className="flex items-center space-x-1">
                        <Clock className="h-3.5 w-3.5 text-slate-600" />
                        <span>Recent Compile</span>
                      </span>
                      <button 
                        onClick={() => onOpenProject(p.id)}
                        className="text-teal-400 hover:text-white font-bold flex items-center space-x-1"
                      >
                        <span>Open Workspace</span>
                        <ArrowUpRight className="h-3 w-3" />
                      </button>
                    </div>
                  </div>
                );
              })}
            </div>
          )}
        </div>

        {/* Right Side: Usage countdown tracker meter */}
        <div className="lg:col-span-4 space-y-4">
          <h2 className="text-sm font-bold text-slate-200 flex items-center space-x-2">
            <Clock className="h-4 w-4 text-purple-400" />
            <span>Usage Allocation Reset</span>
          </h2>

          <div className="p-5 bg-slate-900/40 border border-slate-900 rounded-2xl space-y-5">
            <div className="flex justify-between items-start">
              <div>
                <h3 className="text-xs font-bold text-white">System Auto-Reset</h3>
                <p className="text-[10px] text-slate-500 mt-0.5">Quota resets in: 12h : 45m</p>
              </div>
              <span className="px-2 py-0.5 bg-purple-500/10 text-purple-400 border border-purple-500/20 text-[9px] uppercase font-mono rounded font-bold">
                PRO ACTIVE
              </span>
            </div>

            {/* Simulated Live Terminal Status Log */}
            <div className="bg-slate-950 p-3 rounded-xl border border-slate-900 font-mono text-[9px] text-slate-500 space-y-1.5">
              <div className="flex justify-between text-slate-400">
                <span>[system] COMPILER_ONLINE</span>
                <span className="text-emerald-400 animate-pulse">● LIVE</span>
              </div>
              <p>✔ Nginx reverse proxy OK</p>
              <p>✔ Sandboxed port 3000 mapping OK</p>
              <p>✔ Multi-node replication ready</p>
            </div>

            <div className="pt-3 border-t border-slate-900/60 flex items-center justify-between text-[9px] font-mono text-slate-500">
              <span className="flex items-center space-x-1">
                <RefreshCw className="h-3 w-3 text-emerald-400 animate-spin" style={{ animationDuration: "10s" }} />
                <span>Compiler Status</span>
              </span>
              <span className="text-teal-400 font-bold">STABLE READY</span>
            </div>
          </div>
        </div>

      </div>

      {/* 6. Suggested Templates */}
      <div className="space-y-4 z-10 relative">
        <h2 className="text-sm font-bold text-slate-200 flex items-center space-x-2">
          <Compass className="h-4 w-4 text-cyan-400" />
          <span>Suggested Templates</span>
        </h2>

        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
          {templates.map((tmpl, idx) => (
            <div 
              id={`template-card-${idx}`}
              key={idx}
              className="p-5 bg-slate-900/40 border border-slate-900 rounded-2xl flex flex-col justify-between space-y-4 hover:border-teal-500/20 transition group"
            >
              <div className="space-y-2">
                <span className="text-[9px] font-mono uppercase bg-cyan-500/10 text-cyan-400 px-2 py-0.5 rounded font-bold">
                  STARTER PRE-COMPILE
                </span>
                <h3 className="text-xs sm:text-sm font-extrabold text-white group-hover:text-teal-400 transition">{tmpl.name}</h3>
                <p className="text-slate-400 text-xs leading-relaxed">{tmpl.desc}</p>
              </div>

              <div className="flex items-center justify-between pt-3 border-t border-slate-950 text-[10px] font-mono">
                <span className="text-slate-500">Standard index.html compiled</span>
                <button 
                  onClick={() => onCreateNewProject(tmpl.name, tmpl.desc, tmpl.type, tmpl.files)}
                  className="px-4 py-2 bg-teal-500 hover:bg-teal-400 text-slate-950 font-extrabold rounded-lg flex items-center space-x-1.5 transition cursor-pointer"
                >
                  <span>Deploy Template</span>
                  <ChevronRight className="h-3.5 w-3.5" />
                </button>
              </div>
            </div>
          ))}
        </div>
      </div>

      {/* 7. Daily Challenge & Forge XP Achievements */}
      <div className="space-y-4 z-10 relative">
        <div className="flex items-center justify-between">
          <h2 className="text-sm font-bold text-slate-200 flex items-center space-x-2">
            <span className="text-amber-400 font-bold text-base">🏆</span>
            <span>Daily Quests & Forge XP Badges</span>
          </h2>
          <span className="text-[10px] font-mono text-amber-400 font-bold bg-amber-500/10 px-2 py-0.5 rounded border border-amber-500/20">Streak: 5 Days 🔥 • 1,450 XP</span>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
          {/* Today's Challenge */}
          <div className="p-4 bg-gradient-to-br from-amber-950/20 to-slate-900/60 border border-amber-900/40 rounded-2xl space-y-3">
            <div className="flex justify-between items-center">
              <span className="text-[9px] font-mono text-amber-400 font-bold uppercase tracking-wider bg-amber-500/10 px-2 py-0.5 rounded">Daily Quest</span>
              <span className="text-xs text-amber-400 font-bold">+200 XP</span>
            </div>
            <div>
              <h4 className="text-xs font-bold text-white">Build a CSS Grid Dashboard</h4>
              <p className="text-[10px] text-slate-400 mt-0.5">Deploy a workspace container with defined CSS Grid layout and gap units.</p>
            </div>
            <div className="pt-2 border-t border-amber-900/30 flex items-center justify-between text-[10px]">
              <span className="text-slate-500 font-mono">Progress: 1/1 Done</span>
              <span className="text-emerald-400 font-bold flex items-center gap-1">
                <CheckCircle2 className="h-3 w-3" /> Completed
              </span>
            </div>
          </div>

          {/* Daily AI Tip */}
          <div className="p-4 bg-gradient-to-br from-teal-950/20 to-slate-900/60 border border-teal-900/40 rounded-2xl space-y-3">
            <div className="flex justify-between items-center">
              <span className="text-[9px] font-mono text-teal-400 font-bold uppercase tracking-wider bg-teal-500/10 px-2 py-0.5 rounded">Forge Pro Tip</span>
              <Sparkles className="h-3.5 w-3.5 text-teal-400" />
            </div>
            <div>
              <h4 className="text-xs font-bold text-white">Master Concurrent Terminals</h4>
              <p className="text-[10px] text-slate-400 mt-0.5">Use the bottom terminal bar to launch dev and test processes side by side.</p>
            </div>
            <div className="pt-2 border-t border-teal-900/30 flex items-center justify-between text-[10px]">
              <span className="text-slate-500 font-mono">Topic: Architecture</span>
              <span className="text-teal-400 font-bold">Read & Applied</span>
            </div>
          </div>

          {/* Achievements unlocked */}
          <div className="p-4 bg-slate-900/40 border border-slate-900 rounded-2xl space-y-3">
            <div className="flex justify-between items-center">
              <span className="text-[9px] font-mono text-purple-400 font-bold uppercase tracking-wider bg-purple-500/10 px-2 py-0.5 rounded">Badges (4/6)</span>
              <span className="text-[10px] text-slate-500 font-mono">Forge Level 3</span>
            </div>
            <div className="grid grid-cols-3 gap-2 pt-1">
              <div className="p-1.5 bg-slate-950 rounded-lg text-center border border-amber-500/30" title="First Website Built">
                <span className="text-base block">🌐</span>
                <span className="text-[8px] text-amber-300 font-mono block truncate font-bold">Web Dev</span>
              </div>
              <div className="p-1.5 bg-slate-950 rounded-lg text-center border border-teal-500/30" title="Terminal Mastery">
                <span className="text-base block">⚡</span>
                <span className="text-[8px] text-teal-300 font-mono block truncate font-bold">Term Master</span>
              </div>
              <div className="p-1.5 bg-slate-950 rounded-lg text-center border border-purple-500/30" title="5 Days Active Streak">
                <span className="text-base block">🔥</span>
                <span className="text-[8px] text-purple-300 font-mono block truncate font-bold">5 Streak</span>
              </div>
            </div>
          </div>
        </div>
      </div>

      {/* 8. Recommended Learning Tutorials & Lessons */}
      <div className="space-y-4 z-10 relative">
        <h2 className="text-sm font-bold text-slate-200 flex items-center space-x-2">
          <BookOpen className="h-4 w-4 text-purple-400" />
          <span>Recommended Tutorials & Lessons</span>
        </h2>

        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
          {recommendedLessons.map((les) => (
            <div 
              id={`lesson-card-${les.id}`}
              key={les.id}
              onClick={() => onSelectLesson(les.id)}
              className="p-4 bg-slate-900/30 border border-slate-900 hover:border-purple-500/20 rounded-2xl flex justify-between items-center cursor-pointer transition group"
            >
              <div className="space-y-1 max-w-[80%]">
                <div className="flex items-center space-x-2">
                  <span className="text-[9px] font-mono text-purple-400 uppercase tracking-wider font-bold">{les.difficulty}</span>
                  <span className="text-slate-600 font-mono text-[9px]">•</span>
                  <span className="text-slate-500 font-mono text-[9px]">{les.duration}</span>
                </div>
                <h4 className="text-xs font-extrabold text-white group-hover:text-purple-300 transition truncate">{les.title}</h4>
                <p className="text-[11px] text-slate-400 leading-normal line-clamp-1">{les.desc}</p>
              </div>
              <div className="p-2.5 bg-slate-950 rounded-xl text-purple-400 group-hover:bg-purple-500 group-hover:text-slate-950 transition shrink-0">
                <Play className="h-4 w-4" />
              </div>
            </div>
          ))}
        </div>
      </div>

      {/* Custom Creation Modal */}
      {showCreateModal && (
        <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-slate-950/80 backdrop-blur-sm">
          <div className="w-full max-w-md bg-slate-900 border border-slate-800 rounded-2xl p-6 shadow-2xl space-y-4 animate-in zoom-in-95 duration-200">
            <div className="flex justify-between items-center border-b border-slate-850 pb-3">
              <h3 className="text-xs sm:text-sm font-extrabold text-white">Create Custom Workspace</h3>
              <button 
                onClick={() => setShowCreateModal(false)}
                className="text-slate-400 hover:text-white transition"
              >
                <X className="h-4 w-4" />
              </button>
            </div>

            <form onSubmit={handleCreateProject} className="space-y-4 text-xs">
              <div className="space-y-1.5 text-left">
                <label className="block text-[10px] font-mono uppercase text-slate-400 font-bold">Workspace Name</label>
                <input 
                  type="text" 
                  placeholder="e.g. Flight Simulator Sandbox"
                  value={newProjName}
                  onChange={(e) => setNewProjName(e.target.value)}
                  className="w-full bg-slate-950 border border-slate-850 focus:border-teal-400 rounded-xl py-2 px-3 text-white focus:outline-none transition"
                  required
                />
              </div>

              <div className="space-y-1.5 text-left">
                <label className="block text-[10px] font-mono uppercase text-slate-400 font-bold">Category Type</label>
                <select 
                  value={newProjType}
                  onChange={(e) => setNewProjType(e.target.value as any)}
                  className="w-full bg-slate-950 border border-slate-850 focus:border-teal-400 rounded-xl py-2 px-3 text-white focus:outline-none transition"
                >
                  <option value="Websites">Websites & Apps</option>
                  <option value="Games">Retro Game loops</option>
                  <option value="Images">Creative Graphics</option>
                  <option value="Models">3D OBJ meshes</option>
                </select>
              </div>

              <div className="space-y-1.5 text-left">
                <label className="block text-[10px] font-mono uppercase text-slate-400 font-bold">Description</label>
                <textarea 
                  placeholder="Describe your design parameters..."
                  value={newProjDesc}
                  onChange={(e) => setNewProjDesc(e.target.value)}
                  className="w-full h-16 bg-slate-950 border border-slate-850 focus:border-teal-400 rounded-xl py-2 px-3 text-white focus:outline-none transition resize-none"
                />
              </div>

              <button 
                type="submit"
                className="w-full py-2.5 bg-teal-500 hover:bg-teal-400 text-slate-950 font-extrabold rounded-xl transition cursor-pointer uppercase tracking-wider"
              >
                Build Workspace Now
              </button>
            </form>
          </div>
        </div>
      )}

    </div>
  );
}
